### ISSUE TITLE
Support individual source selection

### ISSUE THREAD

**Issue by karlin** [jacebrowning/gdm#69]
If I have two entries "a" and "b" in `gdm.yml` under `sources`, and I run `gdm update`, I will get the latest rev of both "a" and "b".

I would like to be able to call `gdm update a` and only update "a", leaving "b" untouched.

Could also work for `gdm install`

**Comment by jacebrowning** [comment]
@karlin A version with this feature is available to play with: `$ pip3 install gdm==v0.6.dev1`
