### ISSUE TITLE
`gdm install` shouldn't bump version numbers

### ISSUE THREAD

**Issue by jasich** [jacebrowning/gdm#76]
After running `gdm install` I noticed that the version changed even though the dependency was already installed.  Seems like only upgrade should do this.

![I'M OLD GREG](http://i0.kym-cdn.com/photos/images/original/000/042/277/OldGregg.jpg)

**Comment by jacebrowning** [comment]
Is this specifically referring to cases where a list of dependencies is provided? (e.g. `gdm install dep_a dep_b`)

**Comment by jasich** [comment]
I take this back, this has to have happened from running `gdm upgrade` for a specific dependency.  We had reason to believe that this was from a running of `gdm install`, but after evaluating the commands run I'm pretty sure that gdm upgraded more than the specified dependency.

**Comment by jacebrowning** [comment]
I'm going to consider this a feature request to also apply the dependency filtering behavior (e.g. `gdm update foo bar`) to the locking of those dependency versions. Currently `gdm` will record all dependency versions.

**Comment by jacebrowning** [comment]
@jasich @karlin This should give you the behavior you want: `$ pip3 install gdm==0.7.dev1`

**Comment by jacebrowning** [comment]
This behavior is now available in `0.7`.
