### ISSUE TITLE
Require an option to lock sources

### ISSUE THREAD

**Issue by jacebrowning** [jacebrowning/gdm#78]
I'd like the user to be more explicit about when they want `gdm.yml` to change.

Make `$ gdm update` behave like `$ gdm update --no-lock` by default and add `$ gdm update --lock` as a new option.

Once a source as been locked, it's version will continue to be recorded when `$ gdm update` is run.

**Comment by jacebrowning** [comment]
@Ross-Hunter Thoughts?

**Comment by Ross-Hunter** [comment]
:+1:

**Comment by jacebrowning** [comment]
This was partially fixed by #85.
