### ISSUE TITLE
"gdm install" fails with "remote origin already exists" error

### ISSUE THREAD

**Issue by hdnivara** [jacebrowning/gdm#81]
`gdm install` always fails with `fatal: remote origin already exists` error.

```
$ gdm --version
GDM v0.6

$ cat gdm.yml
location: deps
sources:
- dir: <MY-DEPENDENCY>
  link: lib
  repo: <MY-DEPENDENCY-GIT-URL>
  rev: master

$ gdm install
Installing dependencies...

$ mkdir -p /home/admin/tmp/deps
$ cd /home/admin/tmp/deps

  $ git clone <MY-DEPENDENCY-GIT-URL>
  $ cd <MY-DEPENDENCY>
  $ git remote add origin <MY-DEPENDENCY-GIT-URL>

  IN: '/home/admin/tmp/deps/<MY-DEPENDENCY>'

  RAN: '/usr/bin/git remote add origin <MY-DEPENDENCY-GIT-URL>'

  STDOUT:


  STDERR:
fatal: remote origin already exists.
```

The `gdm install` command adds the remote origin. In cases where the remote origin is already present, gdm tries (ignores on failures) to remove the remote and adds it back. The actual command to remote an origin is `git remote rm origin`, but gdm uses `git remote remove origin`.

I guess this should have been introduced in commit SHA: 27e5d8b1ef67412c1f084294f2b1ed56c0606285 where `git fetch` was replaced with `git remote` commands.

Let me know if you need more information.

I will send in a patch (via pull request) with 'remove' changed to 'rm', shortly. I don't see the above error with this patch and gdm removes/adds remotes as expected.

**Comment by jacebrowning** [comment]
Thanks for catching this! I'll review your PR.
